import type { EntityMeta, EntityType } from '../types/entity.js';

export const ENTITY_FIELD_META: Record<EntityType, EntityMeta> = {
  users: {
    entity: 'users',
    fields: [
      { key: 'id', label: 'ID', type: 'string', sortable: true, filterable: true, searchable: true },
      { key: 'email', label: 'Email', type: 'string', sortable: true, filterable: true, searchable: true },
      { key: 'name', label: 'Name', type: 'string', sortable: true, filterable: true, searchable: true },
      {
        key: 'role',
        label: 'Role',
        type: 'enum',
        sortable: true,
        filterable: true,
        searchable: false,
        enumValues: ['admin', 'manager', 'analyst', 'viewer', 'developer'],
      },
      { key: 'department', label: 'Department', type: 'string', sortable: true, filterable: true, searchable: true },
      {
        key: 'status',
        label: 'Status',
        type: 'enum',
        sortable: true,
        filterable: true,
        searchable: false,
        enumValues: ['active', 'inactive', 'pending', 'suspended'],
      },
      { key: 'createdAt', label: 'Created', type: 'date', sortable: true, filterable: true, searchable: false },
      { key: 'lastLoginAt', label: 'Last Login', type: 'date', sortable: true, filterable: true, searchable: false },
      { key: 'country', label: 'Country', type: 'string', sortable: true, filterable: true, searchable: true },
    ],
  },
  orders: {
    entity: 'orders',
    fields: [
      { key: 'id', label: 'ID', type: 'string', sortable: true, filterable: true, searchable: true },
      { key: 'userId', label: 'User ID', type: 'string', sortable: true, filterable: true, searchable: true },
      { key: 'orderNumber', label: 'Order #', type: 'string', sortable: true, filterable: true, searchable: true },
      {
        key: 'status',
        label: 'Status',
        type: 'enum',
        sortable: true,
        filterable: true,
        searchable: false,
        enumValues: ['pending', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded'],
      },
      { key: 'total', label: 'Total', type: 'number', sortable: true, filterable: true, searchable: false },
      { key: 'currency', label: 'Currency', type: 'string', sortable: true, filterable: true, searchable: false },
      { key: 'itemCount', label: 'Items', type: 'number', sortable: true, filterable: true, searchable: false },
      { key: 'createdAt', label: 'Created', type: 'date', sortable: true, filterable: true, searchable: false },
      { key: 'shippedAt', label: 'Shipped', type: 'date', sortable: true, filterable: true, searchable: false },
    ],
  },
  transactions: {
    entity: 'transactions',
    fields: [
      { key: 'id', label: 'ID', type: 'string', sortable: true, filterable: true, searchable: true },
      { key: 'orderId', label: 'Order ID', type: 'string', sortable: true, filterable: true, searchable: true },
      { key: 'userId', label: 'User ID', type: 'string', sortable: true, filterable: true, searchable: true },
      {
        key: 'type',
        label: 'Type',
        type: 'enum',
        sortable: true,
        filterable: true,
        searchable: false,
        enumValues: ['payment', 'refund', 'chargeback', 'adjustment'],
      },
      { key: 'amount', label: 'Amount', type: 'number', sortable: true, filterable: true, searchable: false },
      {
        key: 'status',
        label: 'Status',
        type: 'enum',
        sortable: true,
        filterable: true,
        searchable: false,
        enumValues: ['completed', 'pending', 'failed', 'reversed'],
      },
      {
        key: 'method',
        label: 'Method',
        type: 'enum',
        sortable: true,
        filterable: true,
        searchable: false,
        enumValues: ['credit_card', 'debit_card', 'bank_transfer', 'paypal', 'crypto'],
      },
      { key: 'createdAt', label: 'Created', type: 'date', sortable: true, filterable: true, searchable: false },
      { key: 'reference', label: 'Reference', type: 'string', sortable: true, filterable: true, searchable: true },
    ],
  },
};
